stages:
  - run
run_docker:
  only:
    - main
  stage: run
  script:
    - sudo docker build -t nextgen .
    - sudo docker ps --quiet --filter="name=nextgen-front" | xargs --no-run-if-empty docker rm -f
    - sudo docker run -dt -p 80:80 --restart always --name nextgen-front nextgen
  tags:
    - job
