version: "3.8"
services:
  postgres:
    container_name: nextgen_dev_postgres_container
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    ports:
      - 5888:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextgen
      POSTGRES_HOST_AUTH_METHOD: trust
